### ISSUE TITLE
Error installing pexpect

### ISSUE THREAD

**Issue by NicuckolasRitz** [eLVee1991/youtubeblock#7]
pi@PiHole:~ $ pip install pexpect
Downloading/unpacking pexpect
  Downloading pexpect-4.6.0-py2.py3-none-any.whl (57kB): 57kB downloaded
Downloading/unpacking ptyprocess>=0.5 (from pexpect)
  Downloading ptyprocess-0.6.0-py2.py3-none-any.whl
Installing collected packages: pexpect, ptyprocess
Compiling /tmp/pip-build-f7DTw7/pexpect/pexpect/_async.py ...
  File "/tmp/pip-build-f7DTw7/pexpect/pexpect/_async.py", line 19
    transport, pw = yield from asyncio.get_event_loop()\
                             ^
SyntaxError: invalid syntax

Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 295, in                                   run
    requirement_set.install(install_options, global_options, root=options.root_p                                  ath)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_fi                                  les
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 214, in move_wheel_                                  files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 204, in clobber
    os.makedirs(destdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/p                                  expect-4.6.0.dist-info'

Storing debug log for failure in /home/pi/.pip/pip.log

**Comment by eLVee1991** [comment]
Try running the command as sudo

sudo pip install pexpect
